//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksTag
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int TagId { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Task Task { get; set; }
    }
}
